# ==============================================================================
# TAPIRS
# A reproducible metabarcoding workflow using snakemake
# ==============================================================================

# conda:
#     "envs/tapirs_blast.yaml"

import pandas as pd
configfile: "config/config.yaml"
# report: "reports/snakemake-report.rst"
# --------------------------------------------------
# Load library and sample information
# --------------------------------------------------

libraries_df = pd.read_table(config['samples'], header = None)  # Pull in libraries and samples from tsv

# Generate library wildcards
LIBRARIES = list(libraries_df[0])  # create list from column of dataframe
LIBRARIES = list(dict.fromkeys(LIBRARIES))  # dipping it into a dictionary to remove duplicates

# Generate samples wildcards
SAMPLES = list(libraries_df[1])  # create list from column of dataframe
SAMPLES = list(dict.fromkeys(SAMPLES))  # dipping it into a dictionary to remove duplicates

# Generate list of legitimate combinations
with open(config['samples']) as infile:
    real_combos = []
    for line in infile:
        real_combos.append(line.strip().replace('\t', '/'))

# ---------------------------------------------------
# Conditional rule all
# ---------------------------------------------------

myoutput = list()

blast = "results/" + config['my_experiment'] + "_blast" + str(config['MLCA_identity']) + ".tsv",
kraken2 = "results/" + config['my_experiment'] + "_kraken2" + str(config['MLCA_identity']) + ".tsv"

if config["analysis_method"] == "blast" or config["analysis_method"] == "both":
    myoutput.append(blast)

if config["analysis_method"] == "kraken2" or config["analysis_method"] == "both":
    myoutput.append(kraken2)

rule all:
    input:
        myoutput

# -----------------------------------------------------
# Rule files
# -----------------------------------------------------

include: "rules/qc.smk"
include: "rules/blast.smk"
include: "rules/lca.smk"
include: "rules/vsearch.smk"

if config["analysis_method"] == "blast" or config["analysis_method"] == "both":
    include: "rules/blast.smk"

if config["analysis_method"] == "kraken2" or config["analysis_method"] == "both":
    include: "rules/kraken2.smk"
