#####   TAPIRS: CONFIGFILE   #####
## Tapirs is highly configurable. Configuration is done before a run from within this file.
## You must customise the next two sections to identify your data (wildcard variables) and database locations.

#---------------------------------------------------
# DATABASE SETUP
#---------------------------------------------------
# Setup databases and set locations here

# KRONA
# requires running : $ ktUpdateTaxonomy

# BLAST
blast_db: "<path to blast_nt_db>" # or set location of database

# KRAKEN
kraken_db: "<path to kraken db>" # or set location of database

# --------------------------------------------------
# WILDCARD VARIABLES
# --------------------------------------------------
# Set experiment-specific variables here

my_experiment: "testing_tapirs" # insert experiment name, no_spaces

libraries: "libraries.tsv"

samples: "samples.tsv"

R: ["R1","R2"]

conda_envs: "tapirs.yaml"


# -----------------------------------------------
# LOCATION OF DATA FILES
# -----------------------------------------------
data_dir: "data" # location of data directory on your file system
            # default is data/ - this should contain 'demultiplexed' directory



# *******************************************************
# Config parameters below here are optional,
# ie, if you don't change then default values will be used
# *******************************************************

# -----------------------------------------------
# FASTP TRIMMING AND MERGING VARIABLES
# -----------------------------------------------
FASTP_max_trim1: "106"
FASTP_max_trim2: "106"
FASTP_trim_front1: "20"
FASTP_trim_front2: "20"
FASTP_len_required: "90" # reads shorter than this will be discarded
FASTP_qual_phred: "30" # quality value that a base is qualified. 30 means phred quality >=Q30 is qualified
FASTP_overlap_len: "90" # length of overlap required for MERGING

# -----------------------------------------------
# BLAST VARIABLES
# -----------------------------------------------
max_trim1: "106" #is this needed in general of is it always 106? not enough metabarcoding knowledge
max_trim2: "106"
overlap_len: "<interger>" # length of overlap required for MERGING
BLAST_Nhits: "50" # Number of descriptions

# -----------------------------------------------
# SIMPLE-LCA VARIABLES
# -----------------------------------------------
SLCA_bitscore: "8"
# '-b''--bitscore', 'bitscore top percentage threshold'
SLCA_id: "80"
# -id identity threshold, required
SLCA_coverage: "80"
# -cov coverage threshold', required=True
SLCA_tophit: "yes"
# -t 'Check the best hit first, if it is above the given threshold the tophit will become the output', required=False, choices=['no', 'yes'], default='no')
SLCA_tid: "99"
# -tid 'identity treshold for the tophit', required=False, default='100'
SLCA_tcov: "100" # -tcov query coverage threshold for the tophit', required=False,  default='100'
SLCA_fh: "environmental"
# -fh filter out hits that contain unwanted taxonomy'
SLCA_flh: "unknown" # -flh', filter lca hits', dest='filterLcaHits', help='ignore this in the lca determination'
