name: metacles
channels:
  - bioconda
  - conda-forge
dependencies:
  - snakemake-minimal =5.2.4
  - python
  - jinja2 =2.10
  # - networkx =2.1
  - matplotlib =2.2.3
  - graphviz =2.38.0
  - git

  # processing sequence reads
  - fastp # sequence trimming and processing
  # - flash # paired end merging
  # - seqkit # format conversion
  # - csvtk # csv file toolkit, used in seqkit stats
  - vsearch # dereplication clustering etc

  # taxonomic ID
  - blast # sequence search
  - kraken2 # kmer search
  - kraken-biom # creates BIOM from kraken output
  - biom-format # converts tsv to BIOM1 or BIOM2
  - krona # html visualisation of taxonomy
