site_name: Tapirs

nav:
  - Home: 'index.md'
  - Setting-up-Tapirs:
    - 'Installation': 'Setting-up-Tapirs/installation.md'
    - 'Setup Tapirs': 'Setting-up-Tapirs/setup.md'
    - 'Problem Solving': 'Setting-up-Tapirs/problem-solving.md'
  - Running-Tapirs:
    - 'Running Tapirs': 'Running-Tapirs/run.md'
    - 'Extending the Workflow': 'Running-Tapirs/extending.md'
    - 'Reproducibiility': 'Running-Tapirs/reproducibility.md'
  - Tutorials:
    - 'Basic blast': 'Tutorials/blast_tutorial.md'
    - 'Kraken2': 'Tutorials/kraken_tutorial.md'
    - 'SINTAX': 'Tutorials/sintax_tutorial.md'
  - About:
    - 'FAQs': 'About/faqs.md'
    - 'Design': 'About/design.md'
    - 'Background': 'About/background.md'

theme: readthedocs

markdown_extensions:
  - admonition # this adds info box functionality
