# ==================================================
#               TAPIRS: CONFIGFILE
# ==================================================

my_experiment: "hull"  # insert experiment name, no_spaces

samples: "config/hull1.tsv"

conda: "../envs/tapirs.yaml"  # leave this unedited

analysis_method: "blast"

# -----------------------------------------------
# LOCATION OF INPUT DATA FILES
# -----------------------------------------------
input_data: "resources/libraries"
# should contain a library directory containing your 
# demultiplexed .fastq.gz sample files for analysis

#---------------------------------------------------
# DATABASE LOCATIONS
#---------------------------------------------------
# Place your reference databases in these locations
# or edit to specify the location

# BLAST
blast_db: "resources/databases/12s_fish_blast_db/12s_fish"
# VSEARCH vsearch_dechimerisation
# point this at the fasta within the blast database
dechim_blast_db: "resources/databases/12s_fish_blast_db/12s_fish.fasta"
# KRAKEN
kraken2_db: "resources/databases/12s_fish_kraken2_db"
# TAXONOMY
taxdump: "resources/databases/new_taxdump"

# -----------------------------------------------
# FASTP TRIMMING AND MERGING VARIABLES
# -----------------------------------------------
FASTP_max_len1: 106  # this is the amplicon size
FASTP_max_len2: 106  # this is the amplicon size
FASTP_trim_front1: 20  # this is the forward primer length
FASTP_trim_front2: 20  # this is the reverse primer length
FASTP_qual_phred: 30  # quality value that a base is qualified. 30 means phred quality >=Q30 is qualified
Fastp_unqualified_percent_limit: 40  # maximum percentage bases allowed to be unqualified
FASTP_window_size: 5  # sliding window size for head and tail quality based cuts
FASTP_len_required: 90  # reads shorter than this will be discarded

FASTP_min_overlap: 30  # minimum percentage overlap required for MERGING
FASTP_max_diff: 5  # maximum percentage difference required for MERGING
FASTP_length_limit: 106 # maximum allowed length required to keep read after MERGING

# -----------------------------------------------
# VSEARCH VARIABLES
# -----------------------------------------------

cluster_method: "denoise"

# dereplication
VSEARCH_minuniqsize: 3
# denoising
VSEARCH_minsize: 1
VSEARCH_unoise_alpha: 2.0
VSEARCH_unoise_id: 0.99
# clustering
VSEARCH_cluster_id: 1
VSEARCH_query_cov: 1
# dechimerisation
VSEARCH_mindiffs: 1
VSEARCH_mindiv: 0.8

# -----------------------------------------------
# BLAST VARIABLES
# -----------------------------------------------
BLAST_max_target_seqs: 20 # Number of descriptions
BLAST_min_perc_ident: 98
BLAST_min_evalue: 1e-20

# ------------------------------------------------
# MLCA VARIABLES
# ------------------------------------------------
MLCA_bitscore: 0
MLCA_identity: 100
MCLA_coverage: 90
MLCA_majority: 80
MLCA_hits: 1

# -----------------------------------------------
# KRAKEN2 VARIABLES
# -----------------------------------------------
kraken2_confidence: 0
kraken2_threads: 5
