name: tapirs

channels:
  - conda-forge
  - bioconda

dependencies:
  - snakemake
  - python>=3.7
  - wget
  - matplotlib
  - graphviz
  - biopython
  - pandas

  # processing sequence reads
  - fastp # sequence trimming and processing
  - vsearch # dereplication clustering etc

  # taxonomic ID and LCA
  - blast>=2.9 # sequence search
  - kraken2 # kmer search

  # reports and outputs
  - biom-format # converts tsv to BIOM format
  - kraken-biom # creates BIOM from kraken output
  - multiqc # creates a report of qc reports
  - seqkit # format conversion and stats reporting
  - csvtk # csv file toolkit, used in seqkit stats
  - recentrifuge # produces graphical taxonomy report

  # packages for R analyses
  - r-vegan
  - r-ape
  - r-dplyr
  - r-ggplot2
  - r-ggfortify
  - r-rcolorbrewer
