name: tapirs_env
channels:
  - anaconda
  - bioconda
  - conda-forge
  - defaults
  - rmg
dependencies:
  - biopython
  - blast
  - fastp
  - flash
  - pandas
  - snakemake
  - vsearch
  - kraken2
  - python
  - krona
  - kraken-biom
  - biom-format
  - seqkit
